# Generated by Django 5.1.3 on 2024-11-15 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fofumapi', '0002_alter_externalapi_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blockchain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=10)),
                ('rpc_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'db_table': 'blockchain',
            },
        ),
        migrations.CreateModel(
            name='Protocol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('blockchain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protocols', to='fofumapi.blockchain')),
            ],
            options={
                'db_table': 'protocol',
            },
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('opportunity_type', models.CharField(choices=[('staking', 'Staking'), ('lending', 'Lending'), ('farming', 'Yield Farming')], max_length=50)),
                ('apy', models.DecimalField(decimal_places=2, max_digits=10)),
                ('risk_score', models.IntegerField()),
                ('liquidity', models.DecimalField(decimal_places=2, max_digits=20)),
                ('token', models.CharField(max_length=50)),
                ('protocol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='fofumapi.protocol')),
            ],
            options={
                'db_table': 'opportunity',
            },
        ),
    ]
