# Generated by Django 5.1.3 on 2024-11-15 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fofumapi', '0003_blockchain_protocol_opportunity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='liquidity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
