# Generated by Django 5.1.3 on 2024-11-18 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fofumapi', '0005_externalapi_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalapi',
            name='access',
            field=models.CharField(max_length=200),
        ),
    ]
